# permissions for end users to view newdeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: new-crd
    app.kubernetes.io/managed-by: kustomize
  name: newdep-viewer-role
rules:
- apiGroups:
  - apps.newcrd.com
  resources:
  - newdeps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.newcrd.com
  resources:
  - newdeps/status
  verbs:
  - get
