# permissions for end users to edit newdeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: new-crd
    app.kubernetes.io/managed-by: kustomize
  name: newdep-editor-role
rules:
- apiGroups:
  - apps.newcrd.com
  resources:
  - newdeps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.newcrd.com
  resources:
  - newdeps/status
  verbs:
  - get
